const dummyData = {
  clinician: {
    id: "clinician",
    label: "Select a Clinician",
    name: "clinician",
    options: ["Jim", "Bob", "Joe", "Jen"],
  },
  office: {
    id: "office",
    label: "Select an Office",
    name: "office",
    options: ["CHC", "FFC"],
  },
  payer: {
    id: "payer",
    label: "Select Payer",
    name: "payer",
    options: ["Blue Cross", "Humana", "Aetna", "United Health Care"],
  },
  denial: {
    id: "denial",
    label: "Reason for Denial",
    name: "denial",
    options: [
      "Patient Responsibility/Deductible",
      "Coverage Terminated",
      "Invalid Prefix",
      "Invalid Modifier",
    ],
  },
  service: {
    id: "serviceDate",
    label: "Date of Service",
    name: "serviceDate",
  },
  eob: {
    id: "eobDate",
    label: "EOB Date",
    name: "eobDate",
  },
  followUpDate: {
    id: "followUpDate",
    label: "Follow Up Date",
    name: "followUpDate",
  },
  payPeriod: {
    id: "payPeriod",
    label: "Pay Period",
    name: "payPeriod",
  },
  entries: [
    {
      id: 1,
      clinician: "Jim",
      office: "CHC",
      name: "Wes Glassmeyer",
      serviceDate: "2021-08-15",
      eobDate: "2021-08-15",
      memberId: "111111",
      claimNumber: "222222",
      payer: "Blue Cross",
      notes: "this that and the other",
      denial: "Patient Responsibility/Deductible",
      resolved: "false",
      followUpDate: "2021-08-15",
      balance: "0",
      payPeriod: "2021-08-15",
    },
    {
      id: 2,
      clinician: "Bob",
      office: "FFC",
      name: "Jane Doe",
      serviceDate: "2021-07-15",
      eobDate: "2021-07-15",
      memberId: "333333",
      claimNumber: "444444",
      payer: "Humana",
      notes: "asd lkji fuerhf nvjskjdf",
      denial: "Coverage Terminated",
      resolved: "true",
      followUpDate: "2021-07-15",
      balance: "100",
      payPeriod: "2021-07-15",
    },
    {
      id: 3,
      clinician: "Joe",
      office: "FFC",
      name: "James Dill",
      serviceDate: "2021-06-15",
      eobDate: "2021-06-15",
      memberId: "555555",
      claimNumber: "666666",
      payer: "Aetna",
      notes: "foo bar fizz buzz",
      denial: "Invalid Prefix",
      resolved: "false",
      followUpDate: "2021-06-15",
      balance: "2000",
      payPeriod: "2021-06-15",
    },
    {
      id: 4,
      clinician: "Jen",
      office: "FFC",
      name: "James Dill",
      serviceDate: "2021-05-15",
      eobDate: "2021-05-15",
      memberId: "555555",
      claimNumber: "777777",
      payer: "Aetna",
      notes: ["scooby dooby doo", "where are you?"],
      denial: "Invalid Modifier",
      resolved: "false",
      followUpDate: "2021-05-15",
      balance: "2000",
      payPeriod: "2021-05-15",
    },
  ],
};

export default dummyData;
